import type { D1DatabaseRepositoryOptions } from "./database-repository-base";
import { D1DatabaseCommentRepository } from "./d1-database-comments";
import { D1DatabaseCoreRepository } from "./d1-database-core";
import { D1DatabaseCsvRepository } from "./d1-database-csv";
import { D1DatabasePermissionRepository } from "./d1-database-permissions";
import { D1DatabaseRecordRepository } from "./d1-database-records";
import { D1DatabaseViewRepository } from "./d1-database-views";

export class D1DatabaseRepository {
  readonly listDatabases: D1DatabaseCoreRepository["listDatabases"];
  readonly createDatabase: D1DatabaseCoreRepository["createDatabase"];
  readonly updateDatabase: D1DatabaseCoreRepository["updateDatabase"];
  readonly deleteDatabase: D1DatabaseCoreRepository["deleteDatabase"];
  readonly createProperty: D1DatabaseCoreRepository["createProperty"];
  readonly updateProperty: D1DatabaseCoreRepository["updateProperty"];
  readonly deleteProperty: D1DatabaseCoreRepository["deleteProperty"];
  readonly createRecord: D1DatabaseRecordRepository["createRecord"];
  readonly getRecord: D1DatabaseRecordRepository["getRecord"];
  readonly listRecords: D1DatabaseRecordRepository["listRecords"];
  readonly searchRecords: D1DatabaseRecordRepository["searchRecords"];
  readonly updateRecord: D1DatabaseRecordRepository["updateRecord"];
  readonly deleteRecord: D1DatabaseRecordRepository["deleteRecord"];
  readonly bulkEditRecords: D1DatabaseRecordRepository["bulkEditRecords"];
  readonly boardMove: D1DatabaseRecordRepository["boardMove"];
  readonly calendarAssign: D1DatabaseRecordRepository["calendarAssign"];
  readonly getDatabase: D1DatabaseViewRepository["getDatabase"];
  readonly createView: D1DatabaseViewRepository["createView"];
  readonly updateView: D1DatabaseViewRepository["updateView"];
  readonly deleteView: D1DatabaseViewRepository["deleteView"];
  readonly createTemplate: D1DatabaseViewRepository["createTemplate"];
  readonly updateTemplate: D1DatabaseViewRepository["updateTemplate"];
  readonly deleteTemplate: D1DatabaseViewRepository["deleteTemplate"];
  readonly applyTemplate: D1DatabaseViewRepository["applyTemplate"];
  readonly createComment: D1DatabaseCommentRepository["createComment"];
  readonly listComments: D1DatabaseCommentRepository["listComments"];
  readonly updateComment: D1DatabaseCommentRepository["updateComment"];
  readonly deleteComment: D1DatabaseCommentRepository["deleteComment"];
  readonly setDatabasePermission: D1DatabasePermissionRepository["setDatabasePermission"];
  readonly setFieldPermission: D1DatabasePermissionRepository["setFieldPermission"];
  readonly importCsv: D1DatabaseCsvRepository["importCsv"];
  readonly exportCsv: D1DatabaseCsvRepository["exportCsv"];

  constructor(db: D1Database, options: Partial<D1DatabaseRepositoryOptions> = {}) {
    const core = new D1DatabaseCoreRepository(db, options);
    const records = new D1DatabaseRecordRepository(db, options);
    const views = new D1DatabaseViewRepository(db, options, records);
    const comments = new D1DatabaseCommentRepository(db, options);
    const permissions = new D1DatabasePermissionRepository(db, options);
    const csv = new D1DatabaseCsvRepository(db, options);

    this.listDatabases = core.listDatabases.bind(core);
    this.createDatabase = core.createDatabase.bind(core);
    this.updateDatabase = core.updateDatabase.bind(core);
    this.deleteDatabase = core.deleteDatabase.bind(core);
    this.createProperty = core.createProperty.bind(core);
    this.updateProperty = core.updateProperty.bind(core);
    this.deleteProperty = core.deleteProperty.bind(core);
    this.createRecord = records.createRecord.bind(records);
    this.getRecord = records.getRecord.bind(records);
    this.listRecords = records.listRecords.bind(records);
    this.searchRecords = records.searchRecords.bind(records);
    this.updateRecord = records.updateRecord.bind(records);
    this.deleteRecord = records.deleteRecord.bind(records);
    this.bulkEditRecords = records.bulkEditRecords.bind(records);
    this.boardMove = records.boardMove.bind(records);
    this.calendarAssign = records.calendarAssign.bind(records);
    this.getDatabase = views.getDatabase.bind(views);
    this.createView = views.createView.bind(views);
    this.updateView = views.updateView.bind(views);
    this.deleteView = views.deleteView.bind(views);
    this.createTemplate = views.createTemplate.bind(views);
    this.updateTemplate = views.updateTemplate.bind(views);
    this.deleteTemplate = views.deleteTemplate.bind(views);
    this.applyTemplate = views.applyTemplate.bind(views);
    this.createComment = comments.createComment.bind(comments);
    this.listComments = comments.listComments.bind(comments);
    this.updateComment = comments.updateComment.bind(comments);
    this.deleteComment = comments.deleteComment.bind(comments);
    this.setDatabasePermission = permissions.setDatabasePermission.bind(permissions);
    this.setFieldPermission = permissions.setFieldPermission.bind(permissions);
    this.importCsv = csv.importCsv.bind(csv);
    this.exportCsv = csv.exportCsv.bind(csv);
  }
}
