export {
  deleteDatabaseById,
  deleteDatabasePropertyById,
  deleteDatabaseTemplateById,
  deleteDatabaseViewById,
  detachNotesFromDatabase,
  duplicateDatabaseNote,
  getDatabaseById,
  getDatabaseFieldPermission,
  getDatabasePropertyById,
  getDatabaseTemplateById,
  getDatabaseViewById,
  insertDatabase,
  insertDatabaseProperty,
  insertDatabaseTemplate,
  insertDatabaseView,
  listDatabaseDuplicateTitleGroups,
  listDatabaseNotes,
  listDatabasePermissions,
  listDatabaseProperties,
  listDatabases,
  listDatabaseTemplates,
  listDatabaseViews,
  listNotePropertyValuesByNoteIds,
  replaceDatabasePermissions,
  updateDatabaseById,
  updateDatabasePropertyById,
  updateDatabaseTemplateById,
  updateDatabaseViewById,
  upsertDatabaseFieldPermission,
  upsertNotePropertyValues,
} from "./legacy";

export type {
  DatabaseFieldPermissionRow,
  DatabasePermissionRow,
  DatabasePropertyRow,
  DatabaseRow,
  DatabaseTemplateRow,
  DatabaseViewRow,
  NotePropertyValueRow,
} from "./legacy";
