export {
  archiveNoteById,
  emptyTrash,
  findNoteByTitle,
  getDailyNoteByDate,
  getGraphData,
  getLatestNoteVersion,
  getNoteById,
  getNoteVersionById,
  getFolderById,
  insertFolder,
  insertNote,
  insertNoteVersion,
  insertTag,
  listBacklinks,
  listFolders,
  listNoteLinks,
  listNotes,
  listNoteVersions,
  listTags,
  markNoteOpened,
  permanentlyDeleteNoteById,
  rebuildNoteLinks,
  replaceNoteTags,
  restoreNoteById,
  softDeleteNoteById,
  unarchiveNoteById,
  updateFolderById,
  updateNoteById,
  deleteFolderById,
} from "./legacy";

export type {
  FolderRow,
  GraphEdgeRow,
  GraphNodeRow,
  NoteLinkRow,
  NoteRow,
  NoteVersionRow,
  NoteWithTagsRow,
  TagRow,
} from "./legacy";
