import type { DatabaseProperty, DatabaseRecord, DatabaseTemplate, DatabaseView } from "@nexus/contracts";

export function DatabaseViewForm({ name, type, properties, position, disabled, onNameChange, onTypeChange, onSubmit }: { name: string; type: DatabaseView["type"]; properties: readonly DatabaseProperty[]; position: number; disabled: boolean; onNameChange(value: string): void; onTypeChange(value: DatabaseView["type"]): void; onSubmit(input: { name: string; type: DatabaseView["type"]; position: number; config: DatabaseView["config"] }): void }) {
  return <section aria-label="视图表单"><h2>创建视图</h2><label>视图名称<input value={name} onChange={(event) => onNameChange(event.target.value)} /></label><label>视图类型<select value={type} onChange={(event) => onTypeChange(event.target.value as DatabaseView["type"])}><option value="table">table</option><option value="board">board</option><option value="calendar">calendar</option></select></label><button type="button" disabled={disabled} onClick={() => onSubmit({ name, type, position, config: { filters: [], sorts: [], grouping: null, visible_columns: properties.map((property) => property.id), page_size: 50, settings: {} } })}>创建视图</button></section>;
}

export function DatabaseTemplateForm({ templates, templateId, name, records, disabled, onTemplateChange, onNameChange, onCreate, onApply }: { templates: readonly DatabaseTemplate[]; templateId: string; name: string; records: readonly DatabaseRecord[]; disabled: boolean; onTemplateChange(value: string): void; onNameChange(value: string): void; onCreate(name: string): void; onApply(templateId: string): void }) {
  return <section aria-label="模板表单"><h2>模板</h2><ul className="database-entity-list">{templates.map((template) => <li key={template.id}><button type="button" className={template.id === templateId ? "active" : ""} onClick={() => onTemplateChange(template.id)}>{template.name}</button></li>)}</ul><label>模板名称<input value={name} onChange={(event) => onNameChange(event.target.value)} /></label><button type="button" disabled={disabled} onClick={() => onCreate(name)}>创建模板</button>{templateId && records.length ? <button type="button" disabled={disabled} onClick={() => onApply(templateId)}>应用所选模板</button> : null}</section>;
}
